server:
  port: 8081
spring:
  data:
    cassandra:
      port: 9042
#      table1:
#        contact-point: localhost
#        keyspace-name: database
#      table2:
      contact-point: localhost
      keyspace-name: spending

grpc:
  port: 5454
  channel:
    show:
      name: 192.168.1.175
      port: 5353
